### ISSUE TITLE
Python 3 support for PyPDF4

### ISSUE THREAD

**Issue by newnone** [claird/PyPDF4#1]
Sorry if I had no other means of putting the question. A few numbered questions about the future of PyPDF4 and Python releases:

1. Should the new code be developed in Python 3?
2. Shall the contributors try to make it compatible with Python 2 or concern themselves with Python 3 only?
3. Does the old code need to retain its compliance with Python 2 only, Python 3 only, or both Python 2 and Python 3?

If the issues page is deemed not very apt for this kind of discussion, I accept to move it elsewhere.

**Comment by claird** [comment]
My instinct is that we ought encourage contributors to focus on Python 3.  I want to offer to ensure that the source actually accepted is backwards compatible to Python 2, and to adjust it as necessary.

I don't understand your "old" and "new" distinction, Oscar.  My intent is that the PyPDF4 trunk always work cleanly with 3.recent and 2.7 (and 2.6?  earlier?).  I think it's on me to maintain that standard.

Does anyone know a strong reason PyPDF4 can't continue to support 2.7?

**Comment by newnone** [comment]
> I don't understand your "old" and "new" distinction, Oscar.

First I asked what standard the newly developed code should follow. Then I inquired into what should be done with the old one - whether it should be actively ported to a full-fledged Python 3 or just kept the way it is.

> and 2.6? earlier?

[The official Python doumentation](https://docs.python.org/3/howto/pyporting.html#drop-support-for-python-2-6-and-older) has a few points againts pre 2.7 releases. It encourages to extend backward support only when strictly necessary.

See also [The Short Explanation](https://docs.python.org/3/howto/pyporting.html#drop-support-for-python-2-6-and-older) at the same page:
>1. Only worry about supporting Python 2.7
>2. Make sure you have good test coverage (coverage.py can help; pip install coverage)
>3. Learn the differences between Python 2 & 3
>4. Use Futurize (or Modernize) to update your code (e.g. pip install future)
>[...]

**Comment by sim0nx** [comment]
As this is a new fork to continue development of pypdf and with PY2 soon being end of life, you might as well support PY3 only (see https://pythonclock.org/), in order to lighten the code-base (remove compatibility code) and use the full feature-set of PY3.

my2c

**Comment by xilopaint** [comment]
I'm in favor of 2.7 support.

**Comment by claird** [comment]
I've changed my mind.

Despite Arthur Pinheiro's explicit follow-up that "I'm in favor of 2.7
support",
and despite my own earlier dalliance with releases even earlier than Py2.7,
I now think the healthiest course for PyPDF4 is to support only Py3.  I do
a *lot* of migrations, and I might be able to supply 2.7 compatibility; the
community as a whole, though, should focus on Py3, in my current view.  How
does that sound to everyone?

Cameron Laird, vice president
We make computers work for people.

**Comment by xilopaint** [comment]
> How does that sound to everyone?

I think it's problematic since not every OS has Python 3 installed. I have created and distributed a workflow for Alfred (a MacOS app) that relies on PyPDF2 and the system Python. At the moment all the user need to get it installed is double-clicking on the workflow file.

If PyPD4 supports Py3 only I will have to ask the user to install Python 3 (MacOS is shipped with Py2 only) and in order to install Py3 he/she will need to install Homebrew first (installing Python directly is a mess). The problem is: mostly users don't know what Python or Homebrew is.

Believe me, rewriting my code with Python 3 would be a joy, my only concern lies on the end-user.

**Comment by claird** [comment]
Thank you, Arthur:  your situation is enough by itself to make me
reconsider.  Now I have to think more ...

**Comment by newnone** [comment]
If I have to express my opinion, shipping backwards-compatible code can be an instructive and even fun experience. I have been deploying unit tests and considerable code tweaks/implementations to the `PyPDF4/filters.py` module so far, and maintaining a keen eye on what can work for Python 2 but not Python 3 and viceversa let me learn a good deal from the transition from Python 2 to Python 3 and the language itself.

My latest commits for PyPDF4 have supported Python 2, and I vote to continue to do so (I have no precise idea of how many Python 2-enabled machines may continue to exist, but I'd better assume they are quite a few).

**Comment by xilopaint** [comment]
> My latest commits for PyPDF4 have supported Python 2, and I vote to continue to do so (I have no precise idea of how many Python 2-enabled machines may continue to exist, but I'd better assume they are quite a few).

What OSes do you know that are shipped with Python 3 only?

**Comment by sim0nx** [comment]
I know of Ubuntu and Arch. But of course a user doesn't care too much as installing Py2 is straightforward on (most?) Linux's. The same holds for most *BSDs. I suppose this is only really a "pain" on OSX and Windows. :-)

https://www.asmeurer.com/python3-presentation/slides.html

**Comment by xilopaint** [comment]
> I suppose this is only really a "pain" on OSX and Windows.

Do you mean 95% of the user base?

**Comment by sim0nx** [comment]
User base of what exactly?

**Comment by newnone** [comment]
>User base of what exactly?

Of Python overall, I assume.

Anyway @sim0nx, ours isn't a matter of whether supporting Python 3 or not. That will surely happen, you haven't to worry about losing Python 3' charm - it'll be there. We are just discussing whether to include Python 2 as well and I see good reasons to do so (I am looking for factual data so that we can avoid speculating on Python' share).

**Comment by newnone** [comment]
>I am looking for factual data so that we can avoid speculating on Python' share

I found some in the [Python Developers Survey 2017 Results](https://www.jetbrains.com/research/python-developers-survey-2017) conducted by JetBrains and the PSF. Unfortunately the report comes from _developers_ data, not from end-users machines. Anyhow, according to this survey we more or less know that:

* [Python 2 is chosen on average by 25% of the respondents](https://www.jetbrains.com/research/python-developers-survey-2017/#python-3-adoption), 30% for web developers and 20% for data scientists alike.
* [49% of the respondents submitted their survey data using Windows](https://www.jetbrains.com/research/python-developers-survey-2017/#developer-profile) (scroll a bit lower), which can have correlations with the OS used for development (the one used to run the end-user code is another thing completely).
* More, that you can see by yourselves.

Personally, I feel that we are on the brink to maintain support for Python 2. A year or two from now we wouldn't have felt the need presumably. For what I've seen, Python 2 takes away some time for sure, but isn't all that hard to enable into one's code.

Altogether, I vote for both Python 2 and 3.

**Comment by newnone** [comment]
>[...] to submit updates that they've tested only under 3, with an attached request for help on backward compatibility

In what sense "with an attached request for help on backward compatibility"? Should these people ask others to have their code tested under Python 2? If that is the case, I would rather enforce to test and develop for version 2 by themselves. Sure, we can give help otherwise, but I wouldn't advertise that as an option.

**Comment by sim0nx** [comment]
This might be interesting to have a look at:
- https://python3statement.org/
- https://github.com/python3statement/python3statement.github.io

**Comment by xilopaint** [comment]
Apple deprecates scripting languages runtimes in the new macOS 10.15, including Python:

> ## Scripting Language Runtimes
> ### Deprecations
> Scripting language runtimes such as Python, Ruby, and Perl are included in macOS for compatibility with legacy software. Future versions of macOS won’t include scripting language runtimes by default, and might require you to install additional packages. If your software depends on scripting languages, it’s recommended that you bundle the runtime within the app. (49764202)
> Use of Python 2.7 isn’t recommended as this version is included in macOS for compatibility with legacy software. Future versions of macOS won’t include Python 2.7. Instead, it’s recommended that you run python3 from within Terminal. (51097165)
> 

Source: https://developer.apple.com/documentation/macos_release_notes/macos_10_15_beta_release_notes#3318257

**Comment by sim0nx** [comment]
Saw that too. So with the coming EOL of PY2 and now this, there is no more reason to stick to PY2 compatibility I guess ;-)

**Comment by xilopaint** [comment]
> Saw that too. So with the coming EOL of PY2 and now this, there is no more reason to stick to PY2 compatibility I guess ;-)

I agree.
