### ISSUE TITLE
Rename encode/decode classes in filters.py

### ISSUE THREAD

**Issue by newnone** [claird/PyPDF4#10]
Many, if not all, of the classes in `PyPDF4/filters.py` have an uncorresponding nomenclature (and a very ugly one indeed), for the operations they perform. Those classes I refer to are ones as `FlateDecode`, `ASCIIHexDecode`, `LZWDecode` etc., but other than simply decoding data, they also encode it in the format they represent. (Some of them have just started doing it in PR #9, where I have included `encode()` methods for the easing out of unit testing.)

I propose to refactor these classes as `*Codec`; for example `FlateCodec`, `ASCIIHexCodec` and so on, for the above-mentioned reason that they cover both operations, encoding and decoding, most of the time.

I have done a preliminary usage test and they are referenced in only a limited fraction of the codebase (most of the time one or two references, possibly in the same source file). Furthermore, the [official PyPDF2 documentation](https://pythonhosted.org/PyPDF2/index.html) has never documented them to the public and I'm left thinking that the external code that depends on them is very limited.

This is a straightforward modification but requires thinking a bit about it in group. But as of now, the names of these classes are almost totally unrepresentative of what they do.

**Comment by claird** [comment]
Oscar, I support the renaming you propose:  to the best of my knowledge, it
will help us.

Cameron Laird, vice president
We make computers work for people.

**Comment by newnone** [comment]
I have already started the work, but I'm setting up a test case to ensure that the transition is smooth and error-free.

**Comment by claird** [comment]
Super!  Thank you, Oscar.

Cameron Laird, vice president
We make computers work for people.

**Comment by newnone** [comment]
Closed with #14.
