### ISSUE TITLE
Shall `PdfFileWriter` and `PdfFileMerger` adopt the same model as `PdfFileReader`?

### ISSUE THREAD

**Issue by newnone** [claird/PyPDF4#22]
A change that I intended to develop was to have `PdfFileWriter` (and consequently, `PdfFileMerger`) take its output argument from `__init__()`, rather than `write()`. That is, with the current setup, one uses `PdfFileWriter` like so:

```
w = PdfFileWriter()    # Note the absence of arguments
# Do stuff...
w.write(outputStream)
```

To be more consisent with what `PdfFileReader` already does, and to what a user of the library normally expects, I'd see more apt:

```
w = PdfFileWriter(outputStream)
# Do stuff...
w.write()    # Note the absence of arguments
```

Pros:
* More clean and standardized instantiation
* Possibility to add `close()`, `isClosed()` and annexed methods
* Uniformed style along with `PdfFileReader`

Cons:
* Major break from previous version. Code that switches from PyPDF2 to PyPDF4 has to change a little

I had already implemented this solution only to revert it a little later. I did not like to impose such style without asking other members first (although I do not see any except me and @claird, and I'll be away from the project soon).

**Comment by claird** [comment]
I recognize it's not-compatible, in the sense that source for applications
which use PyPDF2 and PyPDF4 will diverge.  There'll never be a better time,
though.  Please do so sooner, rather than later.

Is there anything that can help you stay close to PyPDF4, Oscar?  I
understand your professional schedule constrains you.






Cameron Laird, vice president
We make computers work for people.

**Comment by newnone** [comment]
I applied these changes during some of the latest revisions that culminated in [Move output stream argument from `write()` to `__init__()` in `PdfFileMerger`](https://github.com/claird/PyPDF4/commit/cb6f169e12604c45dfb3c43d796660c86011852c).

The test suite passes as before (I only had to introduce a small tweak) but unfortunately it still isn't as solid as it ought to be. I have run the sample scripts manually and whatnot and hey, all looks to work as before.

**Comment by BrickBeard** [comment]
I see this was updated in the documentation, however this has not been implemented into the package code.  After `pip install pypdf4` I still see this in the package source code:

![image](https://user-images.githubusercontent.com/26386708/62632644-6e185780-b8f8-11e9-82b3-db2e967a4b7a.png)
