### ISSUE TITLE
tox cannot run the unit tests

### ISSUE THREAD

**Issue by kurtmckee** [claird/PyPDF4#36]
tox is no longer able to run the unit tests. This is because `tox.ini` has not been updated.

In addition, unsupported versions of Python are currently targeted for testing. PyPDF4 needs to drop support for Python 2.6, 3.3, and 3.4, and needs to add support for 3.6 and 3.7.

Finally, a coverage report needs to be generated so that developers can see what code is being run by the unit tests.

**Comment by newnone** [comment]
>PyPDF4 needs to drop support for Python 2.6, 3.3, and 3.4, and needs to add support for 3.6 and 3.7.

I don't exactly know about minor versions of Python, but I scarcely see any reason to deploy new Py2 code for PyPDF. [Python 2 end](https://pythonclock.org/) is coming.

**Comment by kurtmckee** [comment]
Yep, I know! =) But it's supported by the Python devs through January 1, 2020, so I didn't drop it as a testing target in PyPDF4.

For comparison, Python 3.4 is no longer supported by the Python devs as of two months ago, so I removed it as a testing target.

**Comment by newnone** [comment]
@claird tell us, what are we to do, can we purge Python 2 code from the repo and stop creating new one? The project is still taking a slow pace, and before a public stable release is out I'd like to guess the Python community will be over Py2.

**Comment by xilopaint** [comment]
> @claird tell us, what are we to do, can we purge Python 2 code from the repo and stop creating new one? The project is still taking a slow pace, and before a public stable release is out I'd like to guess the Python community will be over Py2.

WWDC 2019 will be held June 3-7, so we will be able to confirm if macOS will finally adopt Python 3 in the coming upgrade.
