### ISSUE TITLE
`pypdfStr()` may return a unicode object

### ISSUE THREAD

**Issue by kurtmckee** [claird/PyPDF4#43]
In Python 2, `pypdfStr()` may return a `unicode` object, not a `str` object.

**Comment by newnone** [comment]
Same as #41, can you say something about Py3? The interest lies in the fact that the maintainers might lose interest to ship new Py2 code in the future.

**Comment by kurtmckee** [comment]
Testing suggested no problems with Python 3.

I won't be upset when the maintainers decide to drop Python 2 support and remove compatibility code, but @claird stated the compatibility goals for the project in #1 so that's what I'm targeting. =)
